:goal_net: Setup the user command line error handling
Peralban/Plazza pull request #11
Opened 2024-05-21 13:16 UTC by Thomaltarix

I added the command-line error handling.

Now, the tree arguments are handled and stored in a class.
There's getters to access those variables.

For more details, check this issue: #6

2024-05-21 13:34 UTC, Peralban requested changes

2024-05-21 13:34 UTC, Peralban commented on Makefile
> +INCLUDE		=	-I./src/Errors
???????????????????????????????

2024-05-21 13:44 UTC, Thomaltarix commented on Makefile
> +INCLUDE		=	-I./src/Errors
Done

2024-05-21 14:58 UTC, Thomaltarix commented on src/Arguments.cpp
> +Plazza::Arguments::Arguments(int ac, char **av)
Done

2024-05-22 07:19 UTC, landryarki commented on src/Arguments.cpp
> +    }
maybe consider putting displayUsage in the catch ??

2024-05-22 07:25 UTC, Thomaltarix commented on src/Arguments.cpp
> +    }
Done

2024-05-22 08:42 UTC, landryarki requested changes

2024-05-22 08:42 UTC, landryarki commented on src/Arguments.cpp
> +    }
you still need to catch errors of std::stoi std::stof

2024-05-22 08:43 UTC, Thomaltarix commented on src/Arguments.cpp
> +    }
Done

2024-05-22 08:45 UTC, landryarki approved these changes
:prince: nice

2024-05-22 08:46 UTC, merged