:man_cook: Make cook routine
Peralban/Plazza pull request #19
Opened 2024-05-24 13:45 UTC by Peralban

To obtain more details see :
- #14

2024-05-24 14:29 UTC, Thomaltarix requested changes
I don't legit know what to say

2024-05-24 14:42 UTC, Thomaltarix reviewed
There's too many useless pointers, but since we're friday i'll not request it. But check at landry's comments

2024-05-24 14:43 UTC, landryarki requested changes
the cook is a little sus

2024-05-24 14:43 UTC, landryarki commented on src/kitchen/cook.cpp
> +        int pizzaTypeTmp =  std::stoi(messageQueue->pop());
you should check if the message queue is empty.

2024-05-24 14:43 UTC, landryarki commented on src/kitchen/cook.cpp
> +        int pizzaTypeTmp =  std::stoi(messageQueue->pop());
the format of the message you get from the queue is the following : "t s" with
t = [0 .. 9] * (pizza type)
s = [0 .. 9] * (pizza size)

exemple: "16 8"

you should take that into account when analysing the message from the queue

2024-05-24 14:51 UTC, Peralban commented on src/kitchen/cook.cpp
> +        int pizzaTypeTmp =  std::stoi(messageQueue->pop());
I discuss with thomas about that

2024-05-25 11:36 UTC, Thomaltarix commented on src/kitchen/cook.cpp
> +        int pizzaTypeTmp =  std::stoi(messageQueue->pop());
The landry's message didn't pass but check teams to see its message @Peralban

2024-05-25 15:31 UTC, Thomaltarix approved these changes
The stoi could crash but since it's saturday,  we'll fix it later

2024-05-25 15:33 UTC, Peralban commented
> The stoi could crash but since it's saturday, we'll fix it later

The stoi can crash only if the kitchen push shitty string in the queue.

2024-05-25 18:59 UTC, landryarki approved these changes

2024-05-25 18:59 UTC, merged