4 shell reception shell
Peralban/Plazza pull request #5
Opened 2024-05-15 14:45 UTC by landryarki

added a shell function that loop around user input but that nothing atm.

renamed some stuff to make it coherent.

this is a draft for you to tell me how you prefer it to be implemented with the rest of the program

2024-05-16 10:51 UTC, Thomaltarix requested changes
some early changes

2024-05-16 10:51 UTC, Thomaltarix commented on src/shellParser.cpp
> +std::string sizes[] = {"S", "M", "L", "XL", "XXL"};
It should go in an hpp imo

2024-05-16 13:21 UTC, landryarki commented on include/shellParser.hpp
> +    Token &operator=(const Token &token)
:sleeping:

2024-05-16 13:53 UTC, landryarki commented on include/shellParser.hpp
> +    std::string _value;
no, for later use in the program you should  be able to use them  (to make a getter ? not for me :sunglasses: )

2024-05-16 14:10 UTC, landryarki commented on include/shellParser.hpp
> +    std::string _value;
nvm they are now

2024-05-16 15:06 UTC, Thomaltarix reviewed
You missed some code documentation, but overall, it's fine

2024-05-16 15:06 UTC, Thomaltarix commented on include/shellParser.hpp
> +        size_t _pos;
You can add comments here to

2024-05-16 15:06 UTC, Thomaltarix commented on include/shellParser.hpp
> +        std::vector<Token (Parser::*)()> _parsers = {&Parser::parseSemicolon, &Parser::parseSize, &Parser::parseNumber, &Parser::parseType};
You can add comments here to

2024-05-16 15:37 UTC, landryarki commented
i did not comment private methods since i think this is not needed @Thomaltarix

2024-05-16 17:45 UTC, Thomaltarix commented
It's not useful for the the devs since they definitely can't use this function, but it can be useful for us to understand what it does

2024-05-20 07:03 UTC, Thomaltarix approved these changes

2024-05-20 15:06 UTC, Peralban approved these changes

2024-05-20 20:13 UTC, merged